# Configuration for the LLM API
[llm]
api_key = "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"
api_base_url = "https://openrouter.ai/api/v1"
model_name = "moonshotai/kimi-k2:free"
